#!/bin/sh

set -eu

source /etc/bird/envvars

BIRD_RUN_DIR=/run/bird
BIRD_RUN_USER=bird
BIRD_RUN_GROUP=bird

mkdir --parents "$BIRD_RUN_DIR";

if [ -n "$BIRD_RUN_USER" ]; then
    if ! getent passwd $BIRD_RUN_USER >/dev/null; then
	echo "Configured user '$BIRD_RUN_USER' doesn't exist."
	exit 1
    fi
fi

if [ -n "$BIRD_RUN_GROUP" ]; then
    if ! getent group $BIRD_RUN_GROUP >/dev/null; then
	echo "Configured group '$BIRD_RUN_GROUP' doesn't exist."
	exit 1
    fi
fi

chown --silent "$BIRD_RUN_USER:$BIRD_RUN_GROUP" "$BIRD_RUN_DIR"
chmod 775 "$BIRD_RUN_DIR"

:
